export const setFirstAccessFields = {
	HANDLE_INPUT_CLIENT: 'HANDLE_INPUT_CLIENT',
	HANDLE_ADRESS_CLIENT: 'HANDLE_ADRESS_CLIENT',
	HANDLE_PHONE_CLIENT: 'HANDLE_PHONE_CLIENT',

	HANDLE_INPUT_ONG: 'HANDLE_INPUT_ONG',
	HANDLE_ADRESS_ONG: 'HANDLE_ADRESS_ONG',
	HANDLE_PHONE_ONG: 'HANDLE_PHONE_ONG'
};