export const setFirstAccessFields = {
	HANDLE_INPUT_CLIENT: 'HANDLE_INPUT_CLIENT',
	HANDLE_ADRESS_CLIENT: 'HANDLE_ADRESS_CLIENT',
	HANDLE_PHONE_CLIENT: 'HANDLE_PHONE_CLIENT',

	HANDLE_INPUT_ONG: 'HANDLE_INPUT_ONG',
	HANDLE_ADRESS_ONG: 'HANDLE_ADRESS_ONG',
	HANDLE_PHONE_ONG: 'HANDLE_PHONE_ONG',

	HANDLE_INPUT_PET: 'HANDLE_INPUT_PET',
	HANDLE_ADRESS_PET: 'HANDLE_ADRESS_PET',
	HANDLE_PHONE_PET: 'HANDLE_PHONE_PET',
	HANDLE_RESET_INPUT_PET: 'HANDLE_RESET_INPUT_PET'
};