export const ClientActionTypes = {
	CREATE_CLIENT_REQUEST: "CREATE_CLIENT_REQUEST",
	CREATE_CLIENT_SUCCESS: "CREATE_CLIENT_SUCCESS",
	CREATE_CLIENT_FAILURE: "CREATE_CLIENT_FAILURE",

	GET_CLIENT_BY_ID_REQUEST: "GET_CLIENT_BY_ID_REQUEST",
	GET_CLIENT_BY_ID_SUCCESS: "GET_CLIENT_BY_ID_SUCCESS",
	GET_CLIENT_BY_ID_FAILURE: "GET_CLIENT_BY_ID_FAILURE",
};