export const ClientActionTypes = {
	CREATE_CLIENT_REQUEST: "CREATE_CLIENT_REQUEST",
	CREATE_CLIENT_SUCCESS: "CREATE_CLIENT_SUCCESS",
	CREATE_CLIENT_FAILURE: "CREATE_CLIENT_FAILURE",

	UPDATE_CLIENT_REQUEST: "UPDATE_CLIENT_REQUEST",
	UPDATE_CLIENT_SUCCESS: "UPDATE_CLIENT_SUCCESS",
	UPDATE_CLIENT_FAILURE: "UPDATE_CLIENT_FAILURE",

	GET_CLIENT_BY_ID_REQUEST: "GET_CLIENT_BY_ID_REQUEST",
	GET_CLIENT_BY_ID_SUCCESS: "GET_CLIENT_BY_ID_SUCCESS",
	GET_CLIENT_BY_ID_FAILURE: "GET_CLIENT_BY_ID_FAILURE",

	CREATE_ONG_REQUEST: "CREATE_ONG_REQUEST",
	CREATE_ONG_SUCCESS: "CREATE_ONG_SUCCESS",
	CREATE_ONG_FAILURE: "CREATE_ONG_FAILURE",

	UPDATE_ONG_REQUEST: "UPDATE_ONG_REQUEST",
	UPDATE_ONG_SUCCESS: "UPDATE_ONG_SUCCESS",
	UPDATE_ONG_FAILURE: "UPDATE_ONG_FAILURE",

	GET_ONG_BY_ID_REQUEST: "GET_ONG_BY_ID_REQUEST",
	GET_ONG_BY_ID_SUCCESS: "GET_ONG_BY_ID_SUCCESS",
	GET_ONG_BY_ID_FAILURE: "GET_ONG_BY_ID_FAILURE",
};