export const PetActionTypes = {
	CREATE_PET_REQUEST: "CREATE_PET_REQUEST",
	CREATE_PET_SUCCESS: "CREATE_PET_SUCCESS",
	CREATE_PET_FAILURE: "CREATE_PET_FAILURE",

	GET_PET_USER_REQUEST: "GET_PET_USER_REQUEST",
	GET_PET_USER_SUCCESS: "GET_PET_USER_SUCCESS",
	GET_PET_USER_FAILURE: "GET_PET_USER_FAILURE",

	GET_PET_REQUEST: "GET_PET_REQUEST",
	GET_PET_SUCCESS: "GET_PET_SUCCESS",
	GET_PET_FAILURE: "GET_PET_FAILURE",

	GET_PETS_REQUEST: "GET_PETS_REQUEST",
	GET_PETS_SUCCESS: "GET_PETS_SUCCESS",
	GET_PETS_FAILURE: "GET_PETS_FAILURE",

	CREATE_IMG_PET_REQUEST: "CREATE_IMG_PET_REQUEST",
	CREATE_IMG_PET_SUCCESS: "CREATE_IMG_PET_SUCCESS",
	CREATE_IMG_PET_FAILURE: "CREATE_IMG_PET_FAILURE",

	GET_IMG_PET_REQUEST: "GET_IMG_PET_REQUEST",
};