export const TypesHouseActionTypes = {
	GET_TYPES_HOUSE_REQUEST: "GET_TYPES_HOUSE_REQUEST",
	GET_TYPES_HOUSE_SUCCESS: "GET_TYPES_HOUSE_SUCCESS",
	GET_TYPES_HOUSE_FAILURE: "GET_TYPES_HOUSE_FAILURE",
};